#! /bin/bash
session=${1:-dev}
tmux has-session -t $session
if [ $? -ne 0 ]
then
  tmux new-session -s $session -n editor -d
  tmux send-keys -t $session 'vim' C-m
  tmux split-window -v -t $session
  tmux send-keys -t $session:1.2 'test -d .git && gaa && gsta && gup && gstp' C-m
  tmux select-layout -t $session main-vertical
  tmux new-window -n console -t $session
  tmux select-window -t $session:1
fi
tmux attach -t $session
